# from http://docs.travis-ci.com/user/languages/cpp/
language: cpp
compiler: clang
before_install:
    # install gyp
    - sudo apt-get update && sudo apt-get install -y gyp
    # install bru (which depends on python3)
    - sudo apt-get install -y python3
    - git clone https://github.com/KjellSchubert/bru.git
    - sudo ln /home/ubuntu/bru/bru.sh /usr/bin/bru
script:
    # run 'bru install'
    - bru install
    # run 'bru test'
    - bru test
