# from http://docs.travis-ci.com/user/languages/cpp/
language: cpp
compiler: 
    - clang # specifying a version here (like 3.5) makes no diff atm

before_install:
    
    # install gyp
    - sudo apt-get update && sudo apt-get install -y gyp

    # From https://github.com/travis-ci/travis-ci/issues/1379 :
    # The default gcc & stdlib 4.6 as of January 2015, and C++11 sucks
    # with that old stdlib. Let's pull g++ >= 4.8's stdlib instead:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8
    - which g++
    - g++ --version
    # Note that even though this still reports g++ 4.6 clang will end up using
    # the 4.8 stdlib, solving the 4.6 issues with std::chrono and C++11 issues
    # in general.

    # set env vars needed by gyp for explicit compilation with clang
    # (since gcc will not be able to handle -fsanitize=address)
    - which clang++
    - clang++ --version
    #- which g++
    #- g++ --version
    - export CXX=`which clang++`
    - export CC=`which clang`
    - export LINK=`which clang++`
    
    # install bru (which depends on >= python3.2)
    # and ln -s it so it can be invoked conveniently via 'bru ...'
    - sudo apt-get install -y python3
    - git clone https://github.com/KjellSchubert/bru.git
    - sudo ln -s `pwd`/bru/bru.sh /usr/local/bin/bru
    
    # optional: install https://github.com/okkez/coveralls-lcov
    - sudo apt-get install -y lcov

install:
    # it doesnt really matter if you pull deps via 'bru install' during the
    # travis-ci install or script stage, but
    #   http://docs.travis-ci.com/user/build-configuration/
    # suggests the install stage for convention's sake. So let's install
    # upstream dependencies needed during C++ compilation now, e.g.
    # googletest, protobuf, ... Not that pulling deps here implies getting
    # the tar.gz for these modules unpacked, running ./configure for some of 
    # them, but not building them yet. Not that this matters a lot.
    - bru install

script:
    # build & run quick tests for upstream dependencies. These are the tests
    # as specified in bru:library/protobuf_and_such/*.gyp.
    # Since this steps builds all targets in ./*gyp it will also build the test
    # app's own cpp files in ./src
    - bru test
    
    # and run the test in ./src (which wasnt run by 'bru test' which only
    # ran tests for upstream dependencies)
    # All the lcov (and genhtml) lines are for computing unit test code coverage
    # (exactly the same lines can compute test cov for any *.gyp project).
    - lcov --no-external --zerocounters --directory out/
    - lcov --no-external --capture --initial --base-directory . --directory out \
           --output-file coverage_base.info
    - out/Debug/addressbook-test
    - lcov --no-external --capture --base-directory . --directory out \
           --output-file coverage_test.info
    - lcov --add-tracefile coverage_base.info --add-tracefile coverage_test.info \
           --output-file coverage_total.info
    - genhtml --output-directory coverage coverage_total.info
    
    # and test client-server app:
    # TODO: suppy a shorter timeout than travis-ci's default of 10mins without
    # log output.
    - out/Debug/server &
    - out/Debug/client_req
