# from http://docs.travis-ci.com/user/languages/cpp/
language: cpp
compiler: clang
before_install:
    # install gyp
    - sudo apt-get update && sudo apt-get install -y gyp
    # install bru (which depends on >= python3.4)
    # and ln -s it so it can be invoked conveniently via 'bru ...'
    - sudo apt-get install -y python3.4
    - git clone https://github.com/KjellSchubert/bru.git
    - sudo ln -s `pwd`/bru/bru.sh /usr/local/bin/bru
script:
    # run 'bru install'
    - bru install
    # run 'bru test'
    - bru test
